### ISSUE TITLE
How does Parallel::Pipes handle DESTROY?

### ISSUE THREAD

**Issue by KJ7LNW** [skaji/Parallel-Pipes#9]
Hello,

Awesome Perl module!  It does what I've always wanted.

Question:

What happens to the forked children if `$pipes->close` is not called?

**Comment by KJ7LNW** [comment]
FYI, I added my `DESTROY`

```perl
sub DESTROY     
{                                                   
        my $self = shift;
        
        $self->{_pipes}->close() if $self->{_pipes};
}       
```

which can generate errors like this:

```
	(in cleanup) 	(in cleanup)  at /usr/local/share/perl5/Parallel/Pipes.pm line 222 during global destruction.
	(in cleanup) 	(in cleanup)  at /usr/local/share/perl5/Parallel/Pipes.pm line 222 during global destruction.
	(in cleanup) 	(in cleanup)  at /usr/local/share/perl5/Parallel/Pipes.pm line 222 during global destruction.
	(in cleanup) 	(in cleanup)  at /usr/local/share/perl5/Parallel/Pipes.pm line 222 during global destruction.
...
```

...so I'm not sure what the "right" thing is to do, I just want to make sure there aren't any forked children left around when the process exists.

Also adding my own DESTROY caused `$pipes->close` to get stuck printing this forever:

```
wait() unexpectedly returns -1
wait() unexpectedly returns -1
wait() unexpectedly returns -1
...
```

from here:

https://github.com/skaji/Parallel-Pipes/blob/fff30abfbd2ff96c52593711bec3649aa786a170/lib/Parallel/Pipes.pm#L228

So far I don't have any lost processes, so perhaps it's behaving without my intervention.  

Thanks for any commentary you may have.

**Comment by skaji** [comment]
I'm glad you are interested in this module.

If you use this module,
you must call close() by yourself.

By the way, as synopsis says,
I recommend using Parallel::Pipes::App instead, which calls close() properly.

**Comment by KJ7LNW** [comment]
ok, thanks.  I don't think ::App would have worked in my case.  Here is the commit we used to add parallelism with Parallel::Pipes:

https://github.com/KJ7LNW/perl-PDL-Opt-Simplex-Simple/commit/5bfb5fbe6a4461c0aba3203b26ad2b840511384b

**Comment by KJ7LNW** [comment]
by the way, clever using freeze/thaw which makes it easy to program!
